"""empty message

Revision ID: 4f8c311ffd98
Revises: c76ac69798ed
Create Date: 2020-10-01 19:15:46.121797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8c311ffd98'
down_revision = 'c76ac69798ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bets', ['id'])
    op.create_unique_constraint(None, 'bookmakers', ['id'])
    op.add_column('forks', sa.Column('major_bet_id', sa.Integer(), nullable=True))
    op.add_column('forks', sa.Column('minor_bet_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'forks', ['id'])
    op.drop_constraint('forks_major_bet_fkey', 'forks', type_='foreignkey')
    op.drop_constraint('forks_minor_bet_fkey', 'forks', type_='foreignkey')
    op.create_foreign_key(None, 'forks', 'bets', ['minor_bet_id'], ['id'])
    op.create_foreign_key(None, 'forks', 'bets', ['major_bet_id'], ['id'])
    op.drop_column('forks', 'major_bet')
    op.drop_column('forks', 'minor_bet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forks', sa.Column('minor_bet', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('forks', sa.Column('major_bet', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'forks', type_='foreignkey')
    op.drop_constraint(None, 'forks', type_='foreignkey')
    op.create_foreign_key('forks_minor_bet_fkey', 'forks', 'bets', ['minor_bet'], ['id'])
    op.create_foreign_key('forks_major_bet_fkey', 'forks', 'bets', ['major_bet'], ['id'])
    op.drop_constraint(None, 'forks', type_='unique')
    op.drop_column('forks', 'minor_bet_id')
    op.drop_column('forks', 'major_bet_id')
    op.drop_constraint(None, 'bookmakers', type_='unique')
    op.drop_constraint(None, 'bets', type_='unique')
    # ### end Alembic commands ###
