"""empty message

Revision ID: 553992753af5
Revises: 4d599e586fd6
Create Date: 2020-09-18 16:37:36.487098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553992753af5'
down_revision = '4d599e586fd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bookmaker_id', sa.String(), nullable=True),
    sa.Column('match_title', sa.VARCHAR(), nullable=False),
    sa.Column('sport_kind', sa.VARCHAR(), nullable=False),
    sa.Column('championship', sa.VARCHAR(), nullable=False),
    sa.Column('k1', sa.Float(), nullable=False),
    sa.Column('k2', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('forks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('major_bet', sa.String(), nullable=True),
    sa.Column('minor_bet', sa.String(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['major_bet'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['minor_bet'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forks')
    op.drop_table('matches')
    # ### end Alembic commands ###
