"""empty message

Revision ID: a05ead4a194e
Revises: 553992753af5
Create Date: 2020-09-19 11:29:00.669382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a05ead4a194e'
down_revision = '553992753af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmakers', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmakers', 'name')
    # ### end Alembic commands ###
