"""empty message

Revision ID: c76ac69798ed
Revises: 
Create Date: 2020-09-20 19:24:00.481116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c76ac69798ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmakers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('vpn_required', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('bets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=True),
    sa.Column('match_title', sa.VARCHAR(), nullable=False),
    sa.Column('sport_kind', sa.VARCHAR(), nullable=False),
    sa.Column('championship', sa.VARCHAR(), nullable=False),
    sa.Column('k1', sa.Float(), nullable=False),
    sa.Column('k2', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('forks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('major_bet', sa.Integer(), nullable=True),
    sa.Column('minor_bet', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['major_bet'], ['bets.id'], ),
    sa.ForeignKeyConstraint(['minor_bet'], ['bets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forks')
    op.drop_table('bets')
    op.drop_table('bookmakers')
    # ### end Alembic commands ###
